# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model/model.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'model/model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11model/model.proto\x12\x05model\"\x1b\n\x0b\x42\x65rtRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1e\n\x0c\x42\x65rtResponse\x12\x0e\n\x06logits\x18\x01 \x03(\x02\x32\x41\n\x0b\x42\x65rtService\x12\x32\n\x07Predict\x12\x12.model.BertRequest\x1a\x13.model.BertResponseB\x0fZ\r./proto/modelb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model.model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\r./proto/model'
  _globals['_BERTREQUEST']._serialized_start=28
  _globals['_BERTREQUEST']._serialized_end=55
  _globals['_BERTRESPONSE']._serialized_start=57
  _globals['_BERTRESPONSE']._serialized_end=87
  _globals['_BERTSERVICE']._serialized_start=89
  _globals['_BERTSERVICE']._serialized_end=154
# @@protoc_insertion_point(module_scope)
