// Code generated by protoc-gen_go-go. DO NOT EDIT.
// versions:
// 	protoc-gen_go-go v1.36.5
// 	protoc        v5.28.2
// source: proto/model/model.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BertRequest) Reset() {
	*x = BertRequest{}
	mi := &file_proto_model_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BertRequest) ProtoMessage() {}

func (x *BertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BertRequest.ProtoReflect.Descriptor instead.
func (*BertRequest) Descriptor() ([]byte, []int) {
	return file_proto_model_model_proto_rawDescGZIP(), []int{0}
}

func (x *BertRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type BertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logits        []float32              `protobuf:"fixed32,1,rep,packed,name=logits,proto3" json:"logits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BertResponse) Reset() {
	*x = BertResponse{}
	mi := &file_proto_model_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BertResponse) ProtoMessage() {}

func (x *BertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BertResponse.ProtoReflect.Descriptor instead.
func (*BertResponse) Descriptor() ([]byte, []int) {
	return file_proto_model_model_proto_rawDescGZIP(), []int{1}
}

func (x *BertResponse) GetLogits() []float32 {
	if x != nil {
		return x.Logits
	}
	return nil
}

var File_proto_model_model_proto protoreflect.FileDescriptor

var file_proto_model_model_proto_rawDesc = string([]byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x22, 0x21, 0x0a, 0x0b, 0x42, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x22, 0x26, 0x0a, 0x0c, 0x42, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x02, 0x52, 0x06, 0x6c, 0x6f, 0x67, 0x69, 0x74, 0x73, 0x32, 0x41, 0x0a, 0x0b, 0x42,
	0x65, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x50, 0x72,
	0x65, 0x64, 0x69, 0x63, 0x74, 0x12, 0x12, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x42, 0x65,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x42, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0f,
	0x5a, 0x0d, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_model_model_proto_rawDescOnce sync.Once
	file_proto_model_model_proto_rawDescData []byte
)

func file_proto_model_model_proto_rawDescGZIP() []byte {
	file_proto_model_model_proto_rawDescOnce.Do(func() {
		file_proto_model_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_model_model_proto_rawDesc), len(file_proto_model_model_proto_rawDesc)))
	})
	return file_proto_model_model_proto_rawDescData
}

var file_proto_model_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_model_model_proto_goTypes = []any{
	(*BertRequest)(nil),  // 0: model.BertRequest
	(*BertResponse)(nil), // 1: model.BertResponse
}
var file_proto_model_model_proto_depIdxs = []int32{
	0, // 0: model.BertService.Predict:input_type -> model.BertRequest
	1, // 1: model.BertService.Predict:output_type -> model.BertResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_model_model_proto_init() }
func file_proto_model_model_proto_init() {
	if File_proto_model_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_model_model_proto_rawDesc), len(file_proto_model_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_model_model_proto_goTypes,
		DependencyIndexes: file_proto_model_model_proto_depIdxs,
		MessageInfos:      file_proto_model_model_proto_msgTypes,
	}.Build()
	File_proto_model_model_proto = out.File
	file_proto_model_model_proto_goTypes = nil
	file_proto_model_model_proto_depIdxs = nil
}
